sudo: required
dist: trusty
before_install:
  - ./tests/test_setup.sh
language: python
install:
  - python smartcity-middleware.py install -f middleware.conf
  - python smartcity-middleware.py start
script:
  - python ./tests/pytest.py
