---
## sudo apt-get update
  - name: Update repositories
    shell: sudo apk update

  - name: Install locales
    apt: name=locales state=present

  - name: Copy environment file
    copy:
      src: ./config/kong/environment
      dest: /etc/environment
      mode: 0644

  - name: locale create
    shell: locale-gen "en_US.UTF-8"
    become: yes
    become_user: root