---
## Kong Auth Configuration

  - name:  Add file-log plugin to kong
    uri:
      url: http://localhost:8001/plugins/
      method: POST
      body: 'name=file-log&config.path=/tmp/file.json&config.reopen=true'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name:  Add bad-request plugin to kong
    uri:
      url: http://localhost:8001/plugins/
      method: POST
      body: 'name=badrequest'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name:  Add request-size-limiting plugin to kong
    uri:
      url: http://localhost:8001/plugins/
      method: POST
      body: 'name=request-size-limiting&config.allowed_payload_size=0.1'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: (WILL BE REMOVED)  Add consumer guest to kong
    uri:
      url: http://localhost:8001/consumers/
      method: POST
      body: 'username=guest&custom_id=guest'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: (WILL BE REMOVED)  Add consumer guest's apikey
    uri:
      url: http://localhost:8001/consumers/guest/key-auth/
      method: POST
      body: 'key=guest'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: (WILL BE REMOVED)  Add consumer guest to provider
    uri:
      url: http://localhost:8001/consumers/guest/acls
      method: POST
      body: 'group=provider'
      status_code: [201, 409, 400]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409) or (request.status == 400)
    retries: 5

  - name: Creating "/api/1.0.0/register" at kong (http://tomcat:8080)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=register&upstream_url=http://tomcat:8080/RegisterAPI/rest/newregister&uris=/api/1.0.0/register&methods=POST'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/register"
    uri:
        url: http://localhost:8001/apis/register/plugins
        method: POST
        body: 'name=key-auth'
        status_code: [201, 409]
        return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "provider" group to "/api/1.0.0/register"
    uri:
      url: http://localhost:8001/apis/register/plugins
      method: POST
      body: 'name=acl&config.whitelist=provider'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/api/1.0.0/publish" at kong (http://rabbitmq:8000/publish)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=publish&upstream_url=http://rabbitmq:8000/publish&uris=/api/1.0.0/publish&methods=POST'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/publish"
    uri:
      url: http://localhost:8001/apis/publish/plugins
      method: POST
      body: 'name=key-auth'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "publish" group to "/api/1.0.0/publish"
    uri:
      url: http://localhost:8001/apis/publish/plugins
      method: POST
      body: 'name=acl&config.whitelist=publish'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/api/1.0.0/follow" POST at kong (http://kong:8080/follow)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=follow&methods=POST&upstream_url=http://kong:8080/follow&uris=/api/1.0.0/follow'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/follow"
    uri:
      url: http://localhost:8001/apis/follow/plugins
      method: POST
      body: 'name=key-auth'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "subscribe" group to "/api/1.0.0/follow"
    uri:
      url: http://localhost:8001/apis/follow/plugins
      method: POST
      body: 'name=acl&config.whitelist=subscribe'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/api/1.0.0/follow" DELETE at kong (http://kong:8080/follow)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=unfollow&methods=DELETE&upstream_url=http://kong:8080/follow&uris=/api/1.0.0/follow'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/follow"
    uri:
      url: http://localhost:8001/apis/unfollow/plugins
      method: POST
      body: 'name=key-auth'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "subscribe" group to "/api/1.0.0/follow"
    uri:
      url: http://localhost:8001/apis/unfollow/plugins
      method: POST
      body: 'name=acl&config.whitelist=subscribe'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/api/1.0.0/share" POST at kong (http://kong:8080/share)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=share&methods=POST&upstream_url=http://kong:8080/share&uris=/api/1.0.0/share'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/share"
    uri:
      url: http://localhost:8001/apis/share/plugins
      method: POST
      body: 'name=key-auth'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "publish" group to "/api/1.0.0/share"
    uri:
      url: http://localhost:8001/apis/share/plugins
      method: POST
      body: 'name=acl&config.whitelist=publish'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/api/1.0.0/share" DELETE at kong (http://kong:8080/share)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=unshare&methods=DELETE&upstream_url=http://kong:8080/share&uris=/api/1.0.0/share'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/share"
    uri:
      url: http://localhost:8001/apis/unshare/plugins
      method: POST
      body: 'name=key-auth'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "publish" group to "/api/1.0.0/share"
    uri:
      url: http://localhost:8001/apis/unshare/plugins
      method: POST
      body: 'name=acl&config.whitelist=publish'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/api/1.0.0/subscribe?name=q1" at kong (http://rabbitmq:8000/queue?name=q1)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=subscribe&methods=GET&upstream_url=http://rabbitmq:8000/queue&uris=/api/1.0.0/subscribe'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/subscribe?name=q1"
    uri:
        url: http://localhost:8001/apis/subscribe/plugins
        method: POST
        body: 'name=key-auth'
        status_code: [201, 409]
        return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "subscribe" group to "/api/1.0.0/subscribe?name=q1"
    uri:
      url: http://localhost:8001/apis/subscribe/plugins
      method: POST
      body: 'name=acl&config.whitelist=subscribe'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/api/1.0.0/cat" at kong (http://catalogue:8000/cat)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=catGET&methods=GET&upstream_url=http://catalogue:8000/cat&uris=/api/1.0.0/cat'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Creating Catalog-POST API "/api/1.0.0/cat" at kong (http://catalogue:8000/cat)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=catPOST&methods=POST&upstream_url=http://catalogue:8000/cat&uris=/api/1.0.0/cat'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/cat" Catalog-POST API
    uri:
      url: http://localhost:8001/apis/catPOST/plugins
      method: POST
      body: 'name=key-auth'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "provider" group to "/api/1.0.0/cat" Catalog-POST API
    uri:
      url: http://localhost:8001/apis/catPOST/plugins
      method: POST
      body: 'name=acl&config.whitelist=provider'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "database" API at kong
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=database&methods=GET&upstream_url=http://elasticsearch:9200/sensor_data*/_search&uris=/api/1.0.0/db'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/db" to database API
    uri:
      url: http://localhost:8001/apis/database/plugins
      method: POST
      body: 'name=key-auth'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "database" group to "/api/1.0.0/db" database API
    uri:
      url: http://localhost:8001/apis/database/plugins
      method: POST
      body: 'name=acl&config.whitelist=db'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/" at kong (http://tomcat:8080/)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=landing&methods=GET&upstream_url=http://tomcat:8080/RegisterAPI/rest/redirect&uris='
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Creating "/api/1.0.0/register" DELETE at kong (http://kong:8080/register)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=deregister&upstream_url=http://kong:8080/register&uris=/api/1.0.0/register&methods=DELETE'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/register"
    uri:
        url: http://localhost:8001/apis/deregister/plugins
        method: POST
        body: 'name=key-auth'
        status_code: [201, 409]
        return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "provider" group to "/api/1.0.0/register"
    uri:
      url: http://localhost:8001/apis/deregister/plugins
      method: POST
      body: 'name=acl&config.whitelist=provider'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Creating "/api/1.0.0/video.rtmp" GET at kong (http://kong:8080/video)
    uri:
      url: http://localhost:8001/apis/
      method: POST
      body: 'name=video.rtmp&upstream_url=http://kong:8080/video&uris=/api/1.0.0/video.rtmp&methods=GET'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding key-auth to "/api/1.0.0/video.rtmp"
    uri:
        url: http://localhost:8001/apis/video.rtmp/plugins
        method: POST
        body: 'name=key-auth'
        status_code: [201, 409]
        return_content: yes
    register: request
    until: (request.status == 409) or (request.status == 201)
    retries: 5

  - name: Adding acl "subscribe" group to "/api/1.0.0/video.rtmp"
    uri:
      url: http://localhost:8001/apis/video.rtmp/plugins
      method: POST
      body: 'name=acl&config.whitelist=subscribe'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5

  - name: Adding acl "publish" group to "/api/1.0.0/video.rtmp"
    uri:
      url: http://localhost:8001/apis/video.rtmp/plugins
      method: POST
      body: 'name=acl&config.whitelist=publish'
      status_code: [201, 409]
      return_content: yes
    register: request
    until: (request.status == 201) or (request.status == 409)
    retries: 5