---
## Setting up SSH configuration for ansible using user certificates from CA.
#  Creates a 2048-bit SSH key for user root in /root/.ssh/ca-user-certificate-key for user authentication
  - name: Create ca-user-certificate-key
    shell: ssh-keygen -t rsa -b 2048 -f .ssh/ca-user-certificate-key.pub

  # Bring Ansible server's pub file to certificate authority for signing.
  - name: Copy ansible's ssh public key to certificate authority for signing
    copy:
      src: './config/certificate_authority/keys/{{ansible_ssh_public_key}}.pub'
      dest: /root/
      owner: root
      group: root
      mode: 0600

  - name: Copy ansible's public key to home
    shell: cp /root/.ssh/authorized_keys /root/id_rsa.pub

  - name: Sign ansible's public key with ca-user-certificate-key
    shell: ssh-keygen -s /root/.ssh/ca-user-certificate-key -I user_ansible -n ideam,root /root/id_rsa.pub

  - name: Fetch ansible's signed certificate from certificate_authority
    fetch:
      src: '/root/{{ansible_ssh_public_key}}-cert.pub'
      dest: 'config/certificate_authority/keys/{{ansible_ssh_public_key}}-cert.pub'
      flat: yes

  # CA's public key will be distributed to all new hosts.
  - name: Fetch certificate authority's public key for other remote hosts.
    fetch:
      src: '/root/.ssh/ca-user-certificate-key.pub'
      dest: 'config/certificate_authority/keys/ca-user-certificate-key.pub'
      flat: yes

  - name: Remove ansible's ssh public key and certificate in certificate_authority
    file:
      path: "{{ item }}"
      state: absent
    with_items: ['/root/{{ansible_ssh_public_key}}-cert.pub','/root/{{ansible_ssh_public_key}}.pub']

